// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxdanwtrzpfmyvlziopu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4ZGFud3RyenBmbXl2bHppb3B1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1Nzg2NjgsImV4cCI6MjA2NzE1NDY2OH0.J6sZHsjFNkNJ4UWchzadzzeVUvgbpAOZ9fVBwogmhVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});